//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.03 at 03:32:34 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ciscotogo.cisco.com/13/basetypes/order", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cisco.ciscotogo._13.basetypes.order;
